version: '2'
services:
  db:
    #image: mysql:8.0.18
    #container_name: my
    #network_mode: bridge
    #ports:
    #  - 3306:3306
    #environment:
    #  - MYSQL_ROOT_PASSWORD=oroot
    #  - MYSQL_DATABASE=enterprise
    #  - MYSQL_USER=pmuser
    #  - MYSQL_PASSWORD=oroot

    image: postgres:12.1
    container_name: pg
    network_mode: bridge
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=enterprise
      - POSTGRES_USER=postrges
      - POSTGRES_PASSWORD=oroot
    restart: always
  app:
    build: .
    container_name: app
    network_mode: bridge
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5435/enterprise
    #  - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/enterprise
      - SPRING_DATASOURCE_ROOT_PASSWORD=oroot
      - SPRING_DATASOURCE_DATABASE=enterprise
      - SPRING_DATASOURCE_USERNAME=postrges
      - SPRING_DATASOURCE_PASSWORD=oroot
    ports:
      - 8090:8080
    #restart: always
    depends_on:
      - db
    links:
      - db